// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZO5exQpFR48qceJ7eTW3w9jED_ZD_AbI',
    appId: '1:549070430662:web:bd3486cb406f1a621252c7',
    messagingSenderId: '549070430662',
    projectId: 'home-rental-28580',
    authDomain: 'home-rental-28580.firebaseapp.com',
    storageBucket: 'home-rental-28580.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1hqrkfDYx8j6i074I68OybGlISw2VlA',
    appId: '1:549070430662:android:a71c9d688dacf1901252c7',
    messagingSenderId: '549070430662',
    projectId: 'home-rental-28580',
    storageBucket: 'home-rental-28580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAGk4Szpe51Pw0KT0KI_DqXgPvmyqyzjw',
    appId: '1:549070430662:ios:82b760e1dbcc4f4b1252c7',
    messagingSenderId: '549070430662',
    projectId: 'home-rental-28580',
    storageBucket: 'home-rental-28580.appspot.com',
    iosClientId: '549070430662-4fhka9rgmqm4q08bug947hd7ingk18v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.homerental',
  );
}
